name: Issue Close Require

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  close-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Need reproduce
        uses: actions-cool/issues-helper@main
        with:
          actions: 'close-issues'
          labels: '  need reproduce'
          inactive-day: 1
          body: |
            由于该 issue 被标记为需要复现，却 1 天未收到回应。现关闭 issue，若有任何问题，可评论回复。

      - name: Needs more info
        uses: actions-cool/issues-helper@main
        with:
          actions: 'close-issues'
          labels: '  need more info'
          inactive-day: 1
          body: |
            由于该 issue 被标记为需要更多信息，却 1 天未收到回应。现关闭 issue，若有任何问题，可评论回复。
